# Generated by Django 4.1.3 on 2022-12-10 17:45

from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweetusers', '0019_alter_user_username_subscriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptions',
            name='object',
            field=models.ManyToManyField(related_name='subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='subscriptions',
            name='subject',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='User1670694341', error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
        migrations.AddField(
            model_name='subscriptions',
            name='subject',
            field=models.ManyToManyField(related_name='author_subscription', to=settings.AUTH_USER_MODEL),
        ),
    ]
